demo/urls.py
from django.contrib import admin
from django.views import generic
from django.urls import path

from .users import models


urlpatterns = [
    path('', generic.ListView.as_view(
        template_name='index.html',
        queryset=models.User.objects.select_subclasses(),
    )),
    path('employee/add/', generic.CreateView.as_view(
        template_name='form.html',
        model=models.Employee,
        fields=('username', 'hire_date', 'salary', 'department'),
        success_url='/',
    ), name='employee_add'),
    path('employee/<int:pk>/', generic.UpdateView.as_view(
        template_name='form.html',
        model=models.Employee,
        fields=('username', 'hire_date', 'salary', 'department'),
        success_url='/',
    ), name='employee_edit'),
    path('client/add/', generic.CreateView.as_view(
        template_name='form.html',
        model=models.Client,
        fields=('username', 'address', 'zip_code', 'city', 'vip'),
        success_url='/',
    ), name='client_add'),
    path('client/<int:pk>/', generic.UpdateView.as_view(
        template_name='form.html',
        model=models.Client,
        fields=('username', 'address', 'zip_code', 'city', 'vip'),
        success_url='/',
    ), name='client_edit'),
    path('admin/', admin.site.urls),
]

demo/users/models.py
import jsonstore

from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import UserManager
from django.urls import reverse
from polymodels.managers import PolymorphicManager
from polymodels.models import PolymorphicModel


class UserManager(PolymorphicManager, UserManager):
    pass


class User(PolymorphicModel, AbstractUser):
    data = jsonstore.JSONField(null=True, default=dict)
    objects = UserManager()


class Employee(User):
    hire_date = jsonstore.DateField()
    salary = jsonstore.DecimalField(max_digits=10, decimal_places=2)
    department = jsonstore.CharField(max_length=200, choices=[
        ('Marketing', 'Marketing'),
        ('Development', 'Development'),
        ('Sales', 'Sales'),
    ])

    def get_absolute_url(self):
        return reverse('employee_edit', args=[self.pk])

    class Meta:
        proxy = True


class Client(User):
    address = jsonstore.CharField(max_length=250)
    zip_code = jsonstore.CharField(max_length=250)
    city = jsonstore.CharField(max_length=250)
    vip = jsonstore.BooleanField()

    def get_absolute_url(self):
        return reverse('client_edit', args=[self.pk])

    class Meta:
        proxy = True

demo/templates/base.html
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>JSONField Schema Sample</title>
    <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.1/build/pure-min.css">
  </head>
  <body style="display:flex">
      {% block content %}{% endblock %}
  </body>
</html>

demo/templates/form.html
{% extends 'base.html' %}

{% block content %}
<form method="POST" class="pure-form-stacked">
  {% csrf_token %}
  <fieldset>
    <legend>Edit {{ object.content_type|capfirst }}</legend>
    {{ form }}
    <button type="submit" class="pure-button pure-button-primary">Save</button>
  </fielset>
</form>
{% endblock content %}
<form metho="POST">
</form>

demo/templates/index.html
{% extends 'base.html' %}

{% block content %}
<table class="pure-table pure-table-horizontal">
{% for user in user_list %}
<tr>
  <td>{{ user.username }}</td>
  <td>{{ user.content_type }}</td>
  <td>{% with url=user.get_absolute_url %}
      {% if url %}<a href="{{ url }}">edit</a>{% endif %}
  {% endwith %}</td>
</tr>
{% endfor %}
</table>
<div>
  <a class="pure-button" href="{% url 'employee_add' %}">Add an Employee</a>
  <a class="pure-button" href="{% url 'client_add' %}">Add a Client</a>
</div>
{% endblock content %}